### ISSUE TITLE
1.0.1-5 release data missing

### ISSUE THREAD

**Issue by cassidyjames** [JeysonFlores/hasher#10]
Thanks for submitting your 1.0.1-5 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag.

Once you've made the requested changes, create a new release on GitHub and notify us here: https://github.com/elementary/appcenter-reviews/pull/95. You can include the 1.0.1-5 details in the next version's release description since 1.0.1-5 will have never reached users.

As always, if you have any questions you can reply here.

**Comment by JeysonFlores** [comment]
Fixed in #11
