### ISSUE TITLE
Use Gtk.FileChooserNative and the file chooser portal

### ISSUE THREAD

**Issue by danrabbit** [JeysonFlores/hasher#3]
Hey there,

While reviewing you app submission, the filesystem permissions here seem to be quite broad likely due to the use of Gtk.FileChooserDialog instead of [Gtk.FileChooserNative](https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html). Apps should use FileChooserNative so that they make use of the file chooser portal instead of manually adding broader filesystem permissions

**Comment by JeysonFlores** [comment]
Ok, I fixed it now in the (#4) this pull request. Should I make a new release?

**Comment by cassidyjames** [comment]
@JeysonFlores yes, a new release is required to submit a new version to AppCenter.

**Comment by JeysonFlores** [comment]
Yeah, it's already done. It's the [1.0.1-4](https://github.com/JeysonFlores/hasher/releases/tag/1.0.1-4)
